name: Deploy to Zeabur

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Zeabur
        uses: zeabur/action@main
        with:
          project_id: 6a3f6ff522d1fdaf7eb04d04
          service_id: 6a3f700322d1fdaf7eb04d06
          token: ${{ secrets.ZEABUR_TOKEN }}
